/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package erp;

/**
 *
 * @author Sumanth Saligram
 */
public class ERPEmployee extends javax.swing.JInternalFrame {

    /**
     * Creates new form ERPEmployee
     */
    public ERPEmployee() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        newemp = new javax.swing.JButton();
        empdetails = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Employee");
        setMaximumSize(new java.awt.Dimension(626, 507));

        jPanel1.setBackground(new java.awt.Color(56, 77, 144));

        newemp.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        newemp.setForeground(new java.awt.Color(255, 255, 255));
        newemp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/New employee.png"))); // NOI18N
        newemp.setText("New Employee");
        newemp.setBorderPainted(false);
        newemp.setContentAreaFilled(false);
        newemp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newempActionPerformed(evt);
            }
        });

        empdetails.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        empdetails.setForeground(new java.awt.Color(255, 255, 255));
        empdetails.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/employee det.png"))); // NOI18N
        empdetails.setText("Employee Details");
        empdetails.setBorderPainted(false);
        empdetails.setContentAreaFilled(false);
        empdetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empdetailsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(newemp)
                    .addComponent(empdetails))
                .addContainerGap(352, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(newemp)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(empdetails)
                .addContainerGap(227, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void newempActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newempActionPerformed
       ERPnewuser n = new ERPnewuser();
       this.setVisible(false);
       n.setVisible(true);
       
    }//GEN-LAST:event_newempActionPerformed

    private void empdetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empdetailsActionPerformed
       ERPempdetails erp = new ERPempdetails();
       erp.setVisible(true);
    }//GEN-LAST:event_empdetailsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton empdetails;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton newemp;
    // End of variables declaration//GEN-END:variables
}
