/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package erp;

/**
 *
 * @author AVNI
 */
import static java.lang.System.exit;
import static java.lang.Thread.sleep;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import org.jasypt.util.password.StrongPasswordEncryptor;
import java.awt.Image;
import java.awt.Graphics;
import javax.swing.ImageIcon;


public class ERPForgot extends javax.swing.JFrame {
 public Connection con;
    private Statement st;
    private ResultSet rs,rs1;
    private int changecount=0;
    private boolean access=false;
   private String effuname="";
    private String uname="";
    int clickcount=0;
    /**
     * Creates new form ERPForgot
     */
    public ERPForgot() {
        initComponents();
        
        secureq.add("What's your nickname?");
        secureq.add("Where were you born?");
        secureq.add("Which is your hometown?");
        secureq.add("What's your first phone number");
        newpass.setEditable(false);
        confirm.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ImageIcon icon = new ImageIcon(getClass().getResource("/icons/back4.jpg"));
        Image image = icon.getImage();
        forgotdesk = new javax.swing.JDesktopPane(){
            public void paintComponent(Graphics g){
                g.drawImage(image,0,0,getWidth(),getHeight(),this);
            };
        };
        username = new javax.swing.JTextField();
        email = new javax.swing.JTextField();
        answer = new javax.swing.JTextField();
        newpass = new javax.swing.JPasswordField();
        confirm = new javax.swing.JPasswordField();
        secureq = new java.awt.Choice();
        submit = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        newpass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                newpassMousePressed(evt);
            }
        });

        submit.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        submit.setText("Change password");
        submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Enter your username");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Enter your email");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Choose the security question");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Type your answer");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Enter your new Password");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Confirm Password");

        jLabel7.setFont(new java.awt.Font("Sylfaen", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("RESET YOUR PASSWORD");

        forgotdesk.setLayer(username, javax.swing.JLayeredPane.DEFAULT_LAYER);
        forgotdesk.setLayer(email, javax.swing.JLayeredPane.DEFAULT_LAYER);
        forgotdesk.setLayer(answer, javax.swing.JLayeredPane.DEFAULT_LAYER);
        forgotdesk.setLayer(newpass, javax.swing.JLayeredPane.DEFAULT_LAYER);
        forgotdesk.setLayer(confirm, javax.swing.JLayeredPane.DEFAULT_LAYER);
        forgotdesk.setLayer(secureq, javax.swing.JLayeredPane.DEFAULT_LAYER);
        forgotdesk.setLayer(submit, javax.swing.JLayeredPane.DEFAULT_LAYER);
        forgotdesk.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        forgotdesk.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        forgotdesk.setLayer(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        forgotdesk.setLayer(jLabel4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        forgotdesk.setLayer(jLabel5, javax.swing.JLayeredPane.DEFAULT_LAYER);
        forgotdesk.setLayer(jLabel6, javax.swing.JLayeredPane.DEFAULT_LAYER);
        forgotdesk.setLayer(jLabel7, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout forgotdeskLayout = new javax.swing.GroupLayout(forgotdesk);
        forgotdesk.setLayout(forgotdeskLayout);
        forgotdeskLayout.setHorizontalGroup(
            forgotdeskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(forgotdeskLayout.createSequentialGroup()
                .addGroup(forgotdeskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(forgotdeskLayout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addGroup(forgotdeskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(submit)
                            .addGroup(forgotdeskLayout.createSequentialGroup()
                                .addGroup(forgotdeskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6))
                                .addGap(291, 291, 291))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, forgotdeskLayout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(84, 84, 84)
                                .addGroup(forgotdeskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(username, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(secureq, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(answer, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(newpass, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(confirm, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(forgotdeskLayout.createSequentialGroup()
                        .addGap(174, 174, 174)
                        .addComponent(jLabel7)))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        forgotdeskLayout.setVerticalGroup(
            forgotdeskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(forgotdeskLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(forgotdeskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(forgotdeskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(forgotdeskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(secureq, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(forgotdeskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(answer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(forgotdeskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newpass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(forgotdeskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(confirm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addComponent(submit)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(forgotdesk)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(forgotdesk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitActionPerformed

        StrongPasswordEncryptor passcrypt = new StrongPasswordEncryptor();
        try{
            String passupdate = "update erplogin set password=? where username=?";
            PreparedStatement prep2 = con.prepareStatement(passupdate);
            prep2.setString(1,passcrypt.encryptPassword(confirm.getText()));
            prep2.setString(2,uname);
            if(access==true){

                prep2.executeUpdate();
                JOptionPane.showMessageDialog(this, uname.toUpperCase()+" YOUR PASSWORD HAS BEEN CHANGED");}
            else{JOptionPane.showMessageDialog(this, uname.toUpperCase()+"CREDENTIALS ARE WRONG, CHECK AGAIN");}
        }catch(Exception e){}

    }//GEN-LAST:event_submitActionPerformed

    private void newpassMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_newpassMousePressed
        changecount++;
        StrongPasswordEncryptor passcrypt = new StrongPasswordEncryptor();
        try {
            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/erpauth", "root", "");
            st = con.createStatement();
            access=false;
            effuname=username.getText();
            String em=email.getText();
            String seq=secureq.getSelectedItem();
            String ans=answer.getText();
            String query = "select empusername,empemail,empsecureq,empsecureans from erpemp where empusername='"+effuname+"'";
            PreparedStatement prep = con.prepareStatement(query);
            rs = prep.executeQuery();

            if(rs.next()){
                if(effuname.equals(rs.getString("empusername")) &&
                    em.equals(rs.getString("empemail")) &&
                    seq.equals(rs.getString("empsecureq")) &&
                    passcrypt.checkPassword(ans, rs.getString("empsecureans"))){
                    access=true;
                    uname=effuname;
                    newpass.setEditable(true);
                    confirm.setEditable(true);}
                else{newpass.setEditable(false);
                    confirm.setEditable(false);}}
        } catch(Exception ex) {   System.out.println(ex);}

        if(changecount>1){
            if(effuname.isEmpty() && uname.isEmpty()){}
            else{
                if(effuname.equals(uname)){}
                else{
                    newpass.setEnabled(false);
                    confirm.setEnabled(false);
                    access=false;
                    JOptionPane.showMessageDialog(this, "ILLEGAL PASSWORD CHANGE");
                    try{sleep(5);}catch(Exception e){}
                    this.dispose();
                    ERPLoginAuth ea = new ERPLoginAuth();
                    ea.setVisible(true);
                }
            }
        }
    }//GEN-LAST:event_newpassMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ERPForgot.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ERPForgot.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ERPForgot.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ERPForgot.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ERPForgot().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField answer;
    private javax.swing.JPasswordField confirm;
    private javax.swing.JTextField email;
    private javax.swing.JDesktopPane forgotdesk;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPasswordField newpass;
    private java.awt.Choice secureq;
    private javax.swing.JButton submit;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables
}
